---

- hosts: localhost
  become: true
  become_user: root
  become_method: sudo
  pre_tasks:
  - add_host: name=testboot.lxc groups=testboot
  roles:
  - role: novafloss.ssh-agent
    ssh_insecure: ['*.lxc']
  - .

- hosts: testboot
  tasks:
  - shell: uname -a
