---

- hosts: localhost
  become: true
  become_user: root
  become_method: sudo
  pre_tasks:
  - add_host:
      name: testboot.lxc
      groups: testboot
      lxc_container_config:
      - "lxc.mount.entry={{ playbook_dir }} srv none defaults,bind,create=dir,uid=0 0 0"
  roles:
  - role: novafloss.ssh-agent
    ssh_insecure: ['*.lxc']
  - .

- hosts: testboot
  tasks:
  - name: Check that bind mount works, with a bit of inception
    shell: grep inception /srv/test.yml
